apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  ports:
  - port: 80
  selector:
    app: webserver
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ws-cephfs-pvc
  labels:
    app: webserver
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cephfs-demo
  labels:
    app: webserver
    tier: frontend
spec:
  selector:
    matchLabels:
      app: webserver
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: webserver
        ports:
        - containerPort: 80
          name: webserver
        volumeMounts:
        - name: webserver-pvc
          mountPath: /var/lib/www/html
      volumes:
      - name: webserver-pvc
        persistentVolumeClaim:
          claimName: ws-cephfs-pvc
          readOnly: false
