---
# This configuration file is used to describe different sizes
# of deployments.
#
# For each node type define:
# count: Number of nodes of this type
# cpus: Number of CPUs for node
# memory: RAM for node
# extra_disks: Number of extra disks (vdb, vdc) to create,
#              each will have a size of 'disk_Size'
# disk_size: Size of extra disks
minimal:
  nodes:
    master:
      count: 1
      cpus: 2
      memory: 2048
      extra_disks: 0
    worker:
      count: 1
      cpus: 2
      memory: 2048
      extra_disks: 0
    loadbalancer:
      count: 1
      cpus: 1
      memory: 512
      extra_disks: 0
    storage:
      count: 1
      cpus: 1
      memory: 512
      extra_disks: 0
small:
  nodes:
    master:
      count: 1
      cpus: 2
      memory: 2048
      extra_disks: 0
    worker:
      count: 2
      cpus: 2
      memory: 2048
      extra_disks: 0
    loadbalancer:
      count: 1
      cpus: 1
      memory: 1024
      extra_disks: 0
    storage:
      count: 1
      cpus: 1
      memory: 1024
      extra_disks: 0
medium:
  nodes:
    master:
      count: 3
      cpus: 2
      memory: 4096
      extra_disks: 0
    worker:
      count: 3
      cpus: 4
      memory: 16384
      extra_disks: 0
    loadbalancer:
      count: 1
      cpus: 2
      memory: 4096
      extra_disks: 0
    storage:
      count: 1
      cpus: 2
      memory: 4096
      extra_disks: 0
large:
  nodes:
    master:
      count: 3
      cpus: 4
      memory: 8192
      extra_disks: 1
      disk_size: 20G
    worker:
      count: 5
      cpus: 4
      memory: 16384
      extra_disks: 1
      disk_size: 80G
    loadbalancer:
      count: 1
      cpus: 2
      memory: 8192
      extra_disks: 0
    storage:
      count: 1
      cpus: 2
      memory: 8192
      extra_disks: 1
      disk_size: 100G
